.flake8, .github/workflows/tests.yml, .gitignore, nro45_merge/__init__.py, nro45_merge/cli.py, poetry.lock, pyproject.toml, scripts/setup, tests/test_metadata.py
=> Add command line interface

nro45_merge/correlator.py, poetry.lock, pyproject.toml
=> Add correlator module

nro45_merge/correlator.py, tests/test_correlator.py
=> Add conversion from Zarr to VDIF

nro45_merge/correlator.py, tests/test_correlator.py
=> Add chunk length option to VDIF-to-Zarr conversion 

nro45_merge/correlator.py
=> Fix frequency range in correlator module

nro45_merge/accelerometer.py, nro45_merge/weather.py, tests/test_weather.py
=> Fix timezone of weather and accelerometer data

nro45_merge/merge.py, poetry.lock, pyproject.toml
=> Add merge module

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .flake8, .github/workflows/gh-pages.yml, .github/workflows/tests.yml, .gitignore, .vscode/settings.json, LICENSE, docs/build, docs/conf.py, docs/index.md, docs/index.rst, poetry.lock, poetry.toml, pyproject.toml
=> Update project dependencies

mao_merge_45m/antenna.py, mao_merge_45m/weather.py
=> Do not use append method of DataFrame

mao_merge_45m/antenna_50sps.py
=> Add support for new 50-sps antenna logs

mao_merge_45m/__init__.py, mao_merge_45m/sam45.py
=> #37 Add support for SAM45 logs

mao_merge_45m/antenna_50_sps.py
=> #48 Fix timestamp to yymmdd

mao_merge_45m/antenna_50_sps.py
Fixes real_Z1 and real_Z2 in antenna_50_sps.py, lines 196-7.
=> #52 Replace real_Z1 and real_Z2.

mao_merge_45m/sam45.py
=> Update calibration method of SAM45 logs

mao_merge_45m/merge.py
=> Update log paths of merge function to be optional

mao_merge_45m/merge.py, tests/test_merge.py
=> Add argument of SAM45 log path to merge function

mao_merge_45m/merge.py, tests/test_merge.py
=> Add zip option to merge function

mao_merge_45m/accelerometer.py, mao_merge_45m/antenna.py, mao_merge_45m/antenna_50_sps.py, mao_merge_45m/correlator.py, mao_merge_45m/merge.py, mao_merge_45m/sam45.py, mao_merge_45m/weather.py, tests/test_merge.py
=> Make function options keyword-only arguments

mao_merge_45m/sam45.py
=> Fix SAM45 timestamp to datetime64[ns]

README.md, mao_merge_45m/__init__.py, mao_merge_45m/accelerometer_csv.py
=> Add accelerometer_csv module

mao_merge_45m/antenna_50_sps.py
=> Read Az/El values of the collimator from new 50-sps antenna logs

mao_merge_45m/antenna_50_sps.py
=> Read programmed values from new 50-sps antenna logs

mao_merge_45m/merge.py
=> #75 Add options to shift timestamps of logs

mao_merge_45m/merge.py, tests/test_merge.py
=> Fix wrong data_vars/coords assignment in merge module

mao_merge_45m/merge.py
=> Add merge information to merged Zarr

mao_merge_45m/__init__.py, pyproject.toml, tests/test_metadata.py
=> Release v0.2.0

README.md, mao_merge_45m/__init__.py, mao_merge_45m/merge.py, pyproject.toml, tests/test_metadata.py
=> Fix missing long_name of time coordinate

mao_merge_45m/thermometer.py
=> Update thermometer module
